%% Generated by the reporter.pl from TR*.xml


model: UEService:1.0
hrl_guard: UEService
-ifndef(_UEService_HRL_).
-define(_UEService_HRL_, true).
%% @doc: UEService.
-record('UEService',{ 
  'Capabilities'	 :: @Capabilities{},
  'UEContext'	 :: @UEContext{}
}).

%% @doc: UEService.Capabilities.
-record('Capabilities',{ 

}).

%% @doc: UEService.UEContext.
-record('UEContext',{ 
  'PDNConnectionList'	 :: [@PDNConnectionList{}],
  'IMSI' :: string(),
  'EmmState' :: string(),
  'GUTI' :: string(),
  'MeIdentity' :: string(),
  'TaiList' :: string(),
  'LastVisitedTai' :: string(),
  'SelectedNasAlgorithm' :: string(),
  'SelectedAsAlgorithm' :: string(),
  'KSI_ASME' :: string(),
  'K_ASME' :: string(),
  'NasKeysAndCount' :: string(),
  'EUtranUtranKeySetflag' :: string(),
  'TIN' :: string(),
  'UESpecificDrxParameters' :: string(),
  'PDNConnectionListNumberOfEntries' :: unsignedInt()
}).

%% @doc: UEService.UEContext.PDNConnectionList.{i}.
-record('PDNConnectionList',{ 
  'EPSBearerList'	 :: [@EPSBearerList{}],
  'ApnInUse' :: string(),
  'ApnAmbr' :: string(),
  'AssignedPdnType' :: string(),
  'IPAddress' :: IPAddress(),
  'DefaultBearer' :: string(),
  'EPSBearerListNumberOfEntries' :: unsignedInt()
}).

%% @doc: UEService.UEContext.PDNConnectionList.{i}.EPSBearerList.{i}.
-record('EPSBearerList',{ 
  'EPSBearerId' :: unsignedInt(),
  'TI' :: string(),
  'EPSBearerQoS' :: string(),
  'TFT' :: string()
}).

-endif. % _UEService_HRL_
