%% Generated by the reporter.pl from TR*.xml


model: ENBService:1.0
hrl_guard: ENBService
-ifndef(_ENBService_HRL_).
-define(_ENBService_HRL_, true).
%% @doc: ENBService.
-record('ENBService',{ 
  'Capabilities'	 :: @Capabilities{},
  'MobilityManagement'	 :: @MobilityManagement{}
}).

%% @doc: ENBService.Capabilities.
-record('Capabilities',{ 

}).

%% @doc: ENBService.MobilityManagement.
-record('MobilityManagement',{ 
  'UEList'	 :: [@UEList{}],
  'UEListNumberOfEntries' :: unsignedInt()
}).

%% @doc: ENBService.MobilityManagement.UEList.{i}.
-record('UEList',{ 
  'PDNConnectionList'	 :: [@PDNConnectionList{}],
  'CRNTI' :: string(),
  'TAI' :: string(),
  'EmmState' :: string(),
  'ECGI' :: string(),
  'AV' :: string(),
  'UeAmbr' :: unsignedInt(),
  'PDNConnectionListNumberOfEntries' :: unsignedInt()
}).

%% @doc: ENBService.MobilityManagement.UEList.{i}.PDNConnectionList.{i}.
-record('PDNConnectionList',{ 
  'BearerList'	 :: [@BearerList{}],
  'ApnInUse' :: string(),
  'IPAddress' :: IPAddress(),
  'BearerListNumberOfEntries' :: unsignedInt()
}).

%% @doc: ENBService.MobilityManagement.UEList.{i}.PDNConnectionList.{i}.BearerList.{i}.
-record('BearerList',{ 
  'EpsBearerId' :: unsignedInt(),
  'DrbId' :: unsignedInt(),
  'ERabId' :: unsignedInt(),
  'TeidForS1u' :: TEID(),
  'EpsBearerQoS' :: string(),
  'EnbUeS1apId' :: unsignedInt(),
  'MmeUeS1apId' :: unsignedInt(),
  'EnbUeX1apId' :: unsignedInt()
}).

-endif. % _ENBService_HRL_
