%% Generated by the reporter.pl from TR*.xml
%%
%% model: ENBService:1.0
%% hrl_guard: ENBService

-ifndef(_ENBService_HRL_).
-define(_ENBService_HRL_, true).

-include("x-small-cell-types-1-0.hrl").

%% @doc: ENBService.
-record('ENBService',{ 
  'Capabilities'	      :: 'Capabilities'(),
  'MobilityManagement'	      :: 'MobilityManagement'()
}).
-type 'ENBService'() :: #'ENBService'{}. 

%% @doc: ENBService.Capabilities.
-record('Capabilities',{ 

}).
-type 'Capabilities'() :: #'Capabilities'{}. 

%% @doc: ENBService.MobilityManagement.
-record('MobilityManagement',{ 
  'UEList'	 = [] :: 'UEList'(),
  'UEListNumberOfEntries' :: unsignedInt()
}).
-type 'MobilityManagement'() :: #'MobilityManagement'{}. 

%% @doc: ENBService.MobilityManagement.UEList.{i}.
-record('UEList',{ 
  'PDNConnectionList'	 = [] :: 'PDNConnectionList'(),
  'CRNTI' :: string(),
  'TAI' :: string(),
  'EmmState' :: string(),
  'ECGI' :: string(),
  'AV' :: string(),
  'UeAmbr' :: unsignedInt(),
  'PDNConnectionListNumberOfEntries' :: unsignedInt()
}).
-type 'UEList'() :: #'UEList'{}. 

%% @doc: ENBService.MobilityManagement.UEList.{i}.PDNConnectionList.{i}.
-record('PDNConnectionList',{ 
  'BearerList'	 = [] :: 'BearerList'(),
  'ApnInUse' :: string(),
  'IPAddress' :: 'IPAddress'(),
  'BearerListNumberOfEntries' :: unsignedInt()
}).
-type 'PDNConnectionList'() :: #'PDNConnectionList'{}. 

%% @doc: ENBService.MobilityManagement.UEList.{i}.PDNConnectionList.{i}.BearerList.{i}.
-record('BearerList',{ 
  'EpsBearerId' :: unsignedInt(),
  'DrbId' :: unsignedInt(),
  'ERabId' :: unsignedInt(),
  'TeidForS1u' :: TEID(),
  'EpsBearerQoS' :: string(),
  'EnbUeS1apId' :: unsignedInt(),
  'MmeUeS1apId' :: unsignedInt(),
  'EnbUeX1apId' :: unsignedInt()
}).
-type 'BearerList'() :: #'BearerList'{}. 

-endif. % _ENBService_HRL_
