%% Generated by the reporter.pl from TR*.xml
%%
%% model: UEService:1.0
%% hrl_guard: UEService

-ifndef(_UEService_HRL_).
-define(_UEService_HRL_, true).

-include("x-small-cell-types-1-0.hrl").

%% @doc: UEService.
-record('UEService',{ 
  'Capabilities'	      :: 'Capabilities'(),
  'UEContext'	      :: 'UEContext'()
}).
-type 'UEService'() :: #'UEService'{}. 

%% @doc: UEService.Capabilities.
-record('Capabilities',{ 

}).
-type 'Capabilities'() :: #'Capabilities'{}. 

%% @doc: UEService.UEContext.
-record('UEContext',{ 
  'PDNConnectionList'	 = [] :: 'PDNConnectionList'(),
  'IMSI' :: string(),
  'EmmState' :: string(),
  'GUTI' :: string(),
  'MeIdentity' :: string(),
  'TaiList' :: string(),
  'LastVisitedTai' :: string(),
  'SelectedNasAlgorithm' :: string(),
  'SelectedAsAlgorithm' :: string(),
  'KSI_ASME' :: string(),
  'K_ASME' :: string(),
  'NasKeysAndCount' :: string(),
  'EUtranUtranKeySetflag' :: string(),
  'TIN' :: string(),
  'UESpecificDrxParameters' :: string(),
  'PDNConnectionListNumberOfEntries' :: unsignedInt()
}).
-type 'UEContext'() :: #'UEContext'{}. 

%% @doc: UEService.UEContext.PDNConnectionList.{i}.
-record('PDNConnectionList',{ 
  'EPSBearerList'	 = [] :: 'EPSBearerList'(),
  'ApnInUse' :: string(),
  'ApnAmbr' :: string(),
  'AssignedPdnType' :: string(),
  'IPAddress' :: 'IPAddress'(),
  'DefaultBearer' :: string(),
  'EPSBearerListNumberOfEntries' :: unsignedInt()
}).
-type 'PDNConnectionList'() :: #'PDNConnectionList'{}. 

%% @doc: UEService.UEContext.PDNConnectionList.{i}.EPSBearerList.{i}.
-record('EPSBearerList',{ 
  'EPSBearerId' :: unsignedInt(),
  'TI' :: string(),
  'EPSBearerQoS' :: string(),
  'TFT' :: string()
}).
-type 'EPSBearerList'() :: #'EPSBearerList'{}. 

-endif. % _UEService_HRL_
