%% Generated by the reporter.pl from TR*.xml


model: SGWService:1.0
hrl_guard: SGWService
-ifndef(_SGWService_HRL_).
-define(_SGWService_HRL_, true).
%% @doc: SGWService.
-record('SGWService',{ 
  'Capabilities'	 :: @Capabilities{},
  'BM'	 :: @BM{}
}).

%% @doc: SGWService.Capabilities.
-record('Capabilities',{ 

}).

%% @doc: SGWService.BM.
-record('BM',{ 
  'BearerContextList'	 :: [@BearerContextList{}],
  'BearerContextListNumberOfEntries' :: unsignedInt()
}).

%% @doc: SGWService.BM.BearerContextList.{i}.
-record('BearerContextList',{ 
  'PDNConnectionList'	 :: [@PDNConnectionList{}],
  'IMSI' :: string(),
  'MSISDN' :: string(),
  'MmeTeidForS11' :: TEID(),
  'MmeIpAddressForS11' :: IPAddress(),
  'SGwTeidForS11S4' :: TEID(),
  'SGwIpAddressForS11S4' :: IPAddress(),
  'LastKnownCellId' :: string(),
  'LastKnownCellIdAge' :: string(),
  'PDNConnectionListNumberOfEntries' :: unsignedInt()
}).

%% @doc: SGWService.BM.BearerContextList.{i}.PDNConnectionList.{i}.
-record('PDNConnectionList',{ 
  'EPSBearerList'	 :: [@EPSBearerList{}],
  'ApnInUse' :: string(),
  'PGwAddressInUse' :: IPAddress(),
  'SGwIpAddressForS5S8' :: IPAddress(),
  'SGwTeidForS5S8' :: IPAddress(),
  'SGwAddressInUse' :: IPAddress(),
  'DefaultBearer' :: string(),
  'EPSBearerListNumberOfEntries' :: unsignedInt()
}).

%% @doc: SGWService.BM.BearerContextList.{i}.PDNConnectionList.{i}.EPSBearerList.{i}.
-record('EPSBearerList',{ 
  'EPSBearerId' :: unsignedInt(),
  'TFT' :: string(),
  'PGwAddressInUse' :: IPAddress(),
  'PGwTeidForS5S8' :: TEID(),
  'SGwIpAddressForS5S8' :: IPAddress(),
  'SGwTeidForS5S8' :: TEID(),
  'SGwIpAddressForS1uS12andS4' :: IPAddress(),
  'SGwTeidForS1uS12andS4' :: TEID(),
  'eNodeBIpAddressForS1u' :: IPAddress(),
  'eNodeBTeidForS1u' :: TEID(),
  'EPSBearerQoS' :: string()
}).

-endif. % _SGWService_HRL_
