%% Generated by the reporter.pl from TR*.xml
%%
%% model: HSSService:1.0
%% hrl_guard: HSSService

-ifndef(_HSSService_HRL_).
-define(_HSSService_HRL_, true).

-include("x-small-cell-types-1-0.hrl").

%% @doc: HSSService.
-record('HSSService',{ 
  'Capabilities'	      :: 'Capabilities'(),
  'DB'	      :: 'DB'()
}).
-type 'HSSService'() :: #'HSSService'{}. 

%% @doc: HSSService.Capabilities.
-record('Capabilities',{ 

}).
-type 'Capabilities'() :: #'Capabilities'{}. 

%% @doc: HSSService.DB.
-record('DB',{ 
  'SubscriberList'	 = [] :: 'SubscriberList'(),
  'SubscriberListNumberOfEntries' :: unsignedInt()
}).
-type 'DB'() :: #'DB'{}. 

%% @doc: HSSService.DB.SubscriberList.{i}.
-record('SubscriberList',{ 
  'SubscriptionProfileList'	 = [] :: 'SubscriptionProfileList'(),
  'IMSI' :: string(),
  'ImeiImeisv' :: string(),
  'MMEAddress' :: 'IPAddress'(),
  'MsPsPurgedFromEps' :: boolean(),
  'OdbParameters' :: string(),
  'UrrpMme' :: string(),
  'SubscriptionProfileListNumberOfEntries' :: unsignedInt()
}).
-type 'SubscriberList'() :: #'SubscriberList'{}. 

%% @doc: HSSService.DB.SubscriberList.{i}.SubscriptionProfileList.{i}.
-record('SubscriptionProfileList',{ 
  'ContextIdentifier' :: unsignedInt(),
  'PdnAddress' :: 'IPAddress'(),
  'PdnType' :: string(),
  'APN' :: string(),
  'EpsSubscribedQoSProfile' :: string(),
  'SubscribedApnAmbr' :: unsignedInt(),
  'PdnGwidentity' :: 'IPAddress'()
}).
-type 'SubscriptionProfileList'() :: #'SubscriptionProfileList'{}. 

-endif. % _HSSService_HRL_
